id: idea-06-environmental-design-shifts-responsibility-from-the-mind-to-the-surroundings
chapter: '06'
kind: principle
title: Environmental Design Shifts Responsibility From The Mind To The Surroundings
one_liner: Environmental design shifts responsibility from the mind to the surroundings,
  acting as an autopilot [44:33].
description: Environmental design shifts responsibility from the mind to the surroundings,
  acting as an autopilot [44:33]. Strategies include identifying physical supports
  (e.g., readying tools in the workspace) [44:40], removing conflicting triggers (e.g.,
  moving a phone away during deep work), using visual cues (e.g., a checklist), and
  ensuring the social environment (people) reinforces the process.
topics:
- environment
- alignment
- automation
source_refs:
- UBOS/SystemFundamentals/Books/Book02-Build-One-System-at-a-Time/source/chapters/06/chapter.md:3
