id: idea-06-explains-that-a-system-is-much-stronger-when-supported-by-the-physical-and-digital-environment-43
chapter: '06'
kind: principle
title: Explains That A System Is Much Stronger When Supported By The Physical And
  Digital Environment [43
one_liner: This chapter explains that a system is much stronger when supported by
  the physical and digital environment [43:34, 46:57].
description: This chapter explains that a system is much stronger when supported by
  the physical and digital environment [43:34, 46:57]. Environmental design shifts
  responsibility from the mind to the surroundings, acting as an autopilot [44:33].
topics:
- environment
- alignment
- automation
source_refs:
- UBOS/SystemFundamentals/Books/Book02-Build-One-System-at-a-Time/source/chapters/06/chapter.md:3
