id: idea-10-its-in-your-environment
chapter: '10'
kind: principle
title: It'S In Your Environment
one_liner: It's in your environment, your habits, your routines, your allies.
description: It's in your environment, your habits, your routines, your allies. You
  can have the best mindset in the world, but if your surroundings sabotage you, you
  will break.
topics:
- environment
- planning
- execution
source_refs:
- UBOS/SystemFundamentals/Books/Book04-The-Tactical-Mindset/source/chapters/10/chapter.md:3
