#!/bin/bash

# UBOS Codebase Cleanup Script
# Generated by CodebaseAnalyzer

echo "🧹 Starting UBOS codebase cleanup..."

# Remove unused files
echo "📂 Removing unused files..."
# rm ".vscode/settings.json"  # settings.json - unused
# rm "consultant-portal/docs/Analysis.md"  # Analysis.md - unused
# rm "consultant-portal/docs/Pricing.md"  # Pricing.md - unused
# rm "consultant-portal/docs/general/unknown.md"  # unknown.md - unused
# rm "docs/obsidian/.obsidian/appearance.json"  # appearance.json - unused
# rm "docs/obsidian/.obsidian/community-plugins.json"  # community-plugins.json - unused
# rm "logs/test-output/file-writer/1757519667844_k0mw2f0is1m/data/obj.json"  # obj.json - unused
# rm "logs/test-output/file-writer/1757519667844_k0mw2f0is1m/deep/nest/hello.txt"  # hello.txt - unused
# rm "logs/test-output/file-writer/1757625134552_i17tl83a6pr/data/obj.json"  # obj.json - unused
# rm "logs/test-output/file-writer/1757625134552_i17tl83a6pr/deep/nest/hello.txt"  # hello.txt - unused

# Create organized structure
echo "📁 Creating organized directory structure..."
mkdir -p src/{core,agents,integrations,utilities,legacy,tests,docs}
mkdir -p config
mkdir -p scripts

# Move files to organized locations
echo "📋 Organizing files..."

echo "✅ Cleanup complete!"
echo "📊 Run analysis again to see improvements"
