name: Node CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/node-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/node-ci.yml'

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  smoke-perplexity:
    if: ${{ secrets.PERPLEXITY_API_KEY != '' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Perplexity smoke test
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: npm run dev -- perplexity:test "CI ping from EUFM"

  smoke-gemini:
    if: ${{ secrets.GEMINI_API_KEY != '' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Gemini smoke test (flash model)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: gemini-1.5-flash
        run: npm run dev -- gemini:test "CI ping from EUFM"

