id: idea-10-but-over-time-the-environment
chapter: '10'
kind: principle
title: But Over Time The Environment
one_liner: But over time, the environment shapes your habits, your energy levels,
  your focus, and even your identity.
description: But over time, the environment shapes your habits, your energy levels,
  your focus, and even your identity.
topics:
- system
- design
- environment
source_refs:
- UBOS/SystemFundamentals/Books/Book01-BuildTheSystem/source/docs/chapters/10/key-ideas.md:6
