id: idea-10-designing-a-supportive-environment-doesnt
chapter: '10'
kind: principle
title: Designing A Supportive Environment Doesnt
one_liner: Designing a supportive environment doesn't require money.
description: Designing a supportive environment doesn't require money.
topics:
- system
- design
- environment
source_refs:
- UBOS/SystemFundamentals/Books/Book01-BuildTheSystem/source/docs/chapters/10/key-ideas.md:8
