id: idea-16-maintaining-it-requires-regular-evaluation-to-ensure-systems-still-align-with-current-goals-and-values-1
chapter: '16'
kind: principle
title: Maintaining It Requires Regular Evaluation To Ensure Systems Still Align With
  Current Goals And Values [1
one_liner: Maintaining it requires regular evaluation to ensure systems still align
  with current goals and values [1:58:28].
description: Maintaining it requires regular evaluation to ensure systems still align
  with current goals and values [1:58:28]. Flexibility allows the individual to adjust
  their destination without losing momentum [1:59:22].
topics:
- futurecasting
- identity
- alignment
source_refs:
- UBOS/SystemFundamentals/Books/Book02-Build-One-System-at-a-Time/source/chapters/16/chapter.md:3
