id: quote-06-06-environmental-design-shifts-responsibili
chapter: '06'
kind: quote
speaker: Justice O. Malcolm
text: Environmental design shifts responsibility from the mind to the surroundings,
  acting as an autopilot [44:33]. This chapter explains that a system is much stronger
  when supported by the physical and digital environment [43:34, 46:57].
context: Key statement from the chapter.
topics:
- environment
- alignment
source_refs:
- UBOS/SystemFundamentals/Books/Book02-Build-One-System-at-a-Time/source/chapters/06/quotes.md:3
